# Generated by Django 4.0.1 on 2022-02-21 15:07

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Challenge',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Theme_text', models.CharField(max_length=100)),
                ('challenge_date', models.DateTimeField()),
                ('nbr_participants', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Text_chat', models.TextField()),
                ('Text_date', models.DateTimeField()),
            ],
        ),
        migrations.CreateModel(
            name='Module',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_module', models.CharField(max_length=50)),
                ('question_text', models.TextField()),
                ('response_text', models.TextField()),
                ('lien', models.CharField(max_length=150)),
            ],
        ),
    ]
