# Generated by Django 4.0.1 on 2022-02-21 15:10

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='challenge',
            name='challenge_date',
            field=models.DateTimeField(default=datetime.datetime(2022, 2, 21, 15, 10, 22, 802489, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='message',
            name='Text_date',
            field=models.DateTimeField(default=datetime.datetime(2022, 2, 21, 15, 10, 22, 802489, tzinfo=utc)),
        ),
    ]
